name: 'pokemon-tcg'
services:
  db:
    build:
      context: .
      dockerfile: DockerFile.bd
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=process.env.POSTGRES_DB
      - POSTGRES_USER=process.env.POSTGRES_USER
      - POSTGRES_PASSWORD=process.env.POSTGRES_PASSWORD
    ports:
      - '25432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  database:
    driver: local
